### ISSUE TITLE
Uses Psy shell

### ISSUE THREAD

**Issue by szepeviktor** [calebporzio/awesome-helpers#24]
Psy shell is used but psy/psysh is not required.

**Comment by szepeviktor** [comment]
Discovered by @phpstan

`phpstan.neon.dist`

```yaml
# Start command:  phpstan analyze

parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - %currentWorkingDirectory%/src/
    autoload_files:
        - %currentWorkingDirectory%/src/helpers/carbon.php
        - %currentWorkingDirectory%/src/helpers/chain.php
        - %currentWorkingDirectory%/src/helpers/connection.php
        - %currentWorkingDirectory%/src/helpers/dump_sql.php
        - %currentWorkingDirectory%/src/helpers/faker.php
        - %currentWorkingDirectory%/src/helpers/money.php
        - %currentWorkingDirectory%/src/helpers/ok.php
        - %currentWorkingDirectory%/src/helpers/stopwatch.php
        - %currentWorkingDirectory%/src/helpers/str_between.php
        - %currentWorkingDirectory%/src/helpers/str_extract.php
        - %currentWorkingDirectory%/src/helpers/str_match.php
        - %currentWorkingDirectory%/src/helpers/str_validate.php
        - %currentWorkingDirectory%/src/helpers/str_wrap.php
        - %currentWorkingDirectory%/src/helpers/tinker.php
        - %currentWorkingDirectory%/src/helpers/user.php
    ignoreErrors:
        # Laravel mixin.
        - '#^Call to an undefined static method Illuminate\\Support\\Str::[a-z]+\(\)\.$#'
```
